<?xml version="1.0"?>
<adm_context VERSION="0">
  <id NAME="netconf" SERIAL="1">
    <null/>
    <null/>
    </id>
  <datatree>
  <DeviceList TYPE="LIST" ANONYMOUS="TRUE">
    <Device TYPE="LIST">

      <DeviceId TYPE="STRING" VALUE=""/>

      <NMControlled TYPE="BOOL" VALUE="FALSE"/>

      <Device TYPE="STRING" VALUE=""/>
      <Alias TYPE="INT" VALUE="0"/>

      <Type TYPE="STRING" VALUE=""/>
      <SubType TYPE="STRING" VALUE=""/>

      <OnBoot TYPE="BOOL" VALUE="FALSE"/>
      <OnParent TYPE="BOOL" VALUE="FALSE"/>
      <AllowUser TYPE="BOOL" VALUE="FALSE"/>

      <BootProto TYPE="STRING" VALUE=""/>

      <IP TYPE="STRING" VALUE=""/>
      <Netmask TYPE="STRING" VALUE=""/>
      <Gateway TYPE="STRING" VALUE=""/>
      <IPv6Init TYPE="BOOL" VALUE="FALSE"/>

      <Hostname TYPE="STRING" VALUE=""/>
      <Domain TYPE="STRING" VALUE=""/>
      <AutoDNS TYPE="BOOL" VALUE="FALSE"/>

      <HardwareAddress TYPE="STRING" VALUE=""/>

      <Mtu TYPE="INT" VALUE="0"/>

      <Slave TYPE="BOOL" VALUE="FALSE"/>

      <Extra TYPE="LIST">
        </Extra>

      <StaticRoutes TYPE="LIST" ANONYMOUS="TRUE">
        <Route TYPE="LIST">
          <Address TYPE="STRING" VALUE=""/>
          <Netmask TYPE="STRING" VALUE=""/>
          <Gateway TYPE="STRING" VALUE=""/>
          <GatewayDevice TYPE="STRING" VALUE=""/>
          </Route>
        </StaticRoutes>

      <Cipe TYPE="LIST">      
        <TunnelDevice TYPE="STRING" VALUE=""/>
        <TunnelIP TYPE="STRING" VALUE=""/>
        <LocalPort TYPE="INT" VALUE="0"/>
        <RemotePeerAddress TYPE="STRING" VALUE=""/>
        <RemoteVirtualAddress TYPE="STRING" VALUE=""/>
        <SecretKey TYPE="STRING" VALUE=""/>
        </Cipe>

      <Wireless TYPE="LIST">
        <Mode TYPE="STRING" VALUE=""/>
        <EssId TYPE="STRING" VALUE=""/>
        <Channel TYPE="STRING" VALUE=""/>
        <Rate TYPE="STRING" VALUE=""/>
        <Key TYPE="STRING" VALUE=""/>
        </Wireless>

      <Dialup TYPE="LIST">
        <ProviderName TYPE="STRING" VALUE=""/>

        <Login TYPE="STRING" VALUE=""/>
        <Password TYPE="STRING" VALUE=""/>
        <Authentication TYPE="STRING" VALUE=""/>

        <MSN TYPE="STRING" VALUE="0"/>
        <Prefix TYPE="STRING" VALUE=""/>
        <Areacode TYPE="STRING" VALUE=""/>
        <Regioncode TYPE="STRING" VALUE=""/>
        <PhoneNumber TYPE="STRING" VALUE=""/>

        <LocalIP TYPE="STRING" VALUE=""/>        
        <RemoteIP TYPE="STRING" VALUE=""/>        
        <PrimaryDNS TYPE="STRING" VALUE=""/>        
        <SecondaryDNS TYPE="STRING" VALUE=""/>        
        <Persist TYPE="BOOL" VALUE="FALSE"/>
        <DefRoute TYPE="BOOL" VALUE="FALSE"/>
        <Inherits TYPE="STRING" VALUE=""/>

        <ChargeHup TYPE="STRING" VALUE=""/>
        <ChargeInt TYPE="STRING" VALUE=""/>
        <Ihup TYPE="STRING" VALUE=""/>
        <DialMax TYPE="INT" VALUE="3"/>

        <Layer2 TYPE="STRING" VALUE="hdlc"/>
        <Layer3 TYPE="STRING" VALUE="trans"/>

	<Mru TYPE="INT" VALUE="0"/>
		
        <PPPOptions TYPE="LIST" ANONYMOUS="TRUE">
          <PPPOption TYPE="STRING" VALUE=""/>
          </PPPOptions>

        <StupidMode TYPE="BOOL" VALUE="FALSE"/>

        <DialinServer TYPE="BOOL" VALUE="FALSE"/>
        <ChannelBundling TYPE="BOOL" VALUE="FALSE"/>
        <EncapMode TYPE="STRING" VALUE=""/>
        <HangupTimeout TYPE="INT" VALUE="360"/>
        <DialMode TYPE="STRING" VALUE="manual"/>

        <SlaveDevice TYPE="STRING" VALUE=""/>

        <EthDevice TYPE="STRING" VALUE=""/>    
        <ServiceName TYPE="STRING" VALUE=""/>    
        <AcName TYPE="STRING" VALUE=""/>    
        <SyncPPP TYPE="BOOL" VALUE="FALSE"/>    

        <InitString TYPE="STRING" VALUE=""/>

        <Secure TYPE="BOOL" VALUE="FALSE"/>
        <PhoneInNumber TYPE="STRING" VALUE=""/>

        <Callback TYPE="LIST">
          <Delay TYPE="INT" VALUE="3"/>
          <Hup TYPE="BOOL" VALUE="FALSE"/>
          <Compression TYPE="BOOL" VALUE="FALSE"/>
          <Type TYPE="STRING" VALUE="on"/>
          <MSN TYPE="STRING" VALUE=""/>
          </Callback>

        <Compression TYPE="LIST">
          <VJTcpIp TYPE="BOOL" VALUE="FALSE"/>
          <VJID TYPE="BOOL" VALUE="FALSE"/>
          <AdressControl TYPE="BOOL" VALUE="FALSE"/>
          <ProtoField TYPE="BOOL" VALUE="FALSE"/>
          <BSD TYPE="BOOL" VALUE="FALSE"/>
          <CCP TYPE="BOOL" VALUE="FALSE"/>
          </Compression>        
        </Dialup>

      </Device>
    </DeviceList>
    </datatree>
  </adm_context>
 
