<?xml version="1.0"?>
<adm_context VERSION="0">
  <id NAME="netconf" SERIAL="1">
    <null/>
    <null/>
    </id>
  <datatree>
  <Firewall TYPE="LIST">

    <GUIMode TYPE="STRING" VALUE=""/>

    <EasySetup TYPE="LIST">
      <Level TYPE="STRING" VALUE=""/>
      <ServiceList TYPE="LIST" ANONYMOUS="TRUE">
        <ServiceName TYPE="STRING" VALUE=""/>
        </ServiceList>
      <SecureDeviceList TYPE="LIST" ANONYMOUS="TRUE">
        <DeviceId TYPE="STRING" VALUE=""/>
        </SecureDeviceList>
      </EasySetup>

    <MediumSetup TYPE="LIST">
      <InDeviceList TYPE="LIST" ANONYMOUS="TRUE">
        <DeviceId TYPE="STRING" VALUE=""/>
        </InDeviceList>

      <OuterDeviceList TYPE="LIST" ANONYMOUS="TRUE">
        <DeviceId TYPE="STRING" VALUE=""/>
        </OuterDeviceList>

      <MasqList TYPE="LIST" ANONYMOUS="TRUE">
        <MasqEntry TYPE="LIST">
          <InDevice TYPE="STRING" VALUE=""/>
          <OutDevice TYPE="STRING" VALUE=""/>
          <Ports TYPE="STRING" VALUE=""/>
          </MasqEntry>
        </MasqList>
      </MediumSetup>

    <ChainList TYPE="LIST" ANONYMOUS="TRUE">
      <Chain TYPE="LIST">
        <Name TYPE="STRING" VALUE=""/>
        <Table TYPE="STRING" VALUE=""/>
        <Policy TYPE="STRING" VALUE=""/>
        </Chain>
      </ChainList>

    <RuleList TYPE="LIST" ANONYMOUS="TRUE">
      <Rule TYPE="LIST">
        <RuleName  TYPE="STRING" VALUE=""/>
        <RuleGroup  TYPE="STRING" VALUE=""/>
        <Protocol TYPE="STRING" VALUE=""/>
        <Source TYPE="STRING" VALUE=""/>
        <Destination TYPE="STRING" VALUE=""/>
        <Jump TYPE="STRING" VALUE=""/>
        <Chain TYPE="STRING" VALUE=""/>
        <InInterface TYPE="STRING" VALUE=""/>
        <OutInterface TYPE="STRING" VALUE=""/>
        <Fragment TYPE="STRING" VALUE=""/>
        <MatchList TYPE="LIST" ANONYMOUS="TRUE">
          <Match TYPE="LIST">
            <Tcp TYPE="LIST">
              <SourcePorts TYPE="STRING" VALUE=""/>
              <DestPorts TYPE="STRING" VALUE=""/>
              <TcpFlags TYPE="STRING" VALUE=""/>
              <Syn TYPE="STRING" VALUE=""/>
              <TcpOption TYPE="STRING" VALUE=""/>
              </Tcp>
            <Udp TYPE="LIST">
              <SourcePorts TYPE="STRING" VALUE=""/>
              <DestPorts TYPE="STRING" VALUE=""/>
              </Udp>
            <Icmp TYPE="LIST">
              <IcmpType TYPE="STRING" VALUE=""/>
              </Icmp>
            <Mac TYPE="LIST">
              <MacSource TYPE="STRING" VALUE=""/>
              </Mac>
            <Limit TYPE="LIST">
              <Rate TYPE="STRING" VALUE=""/>
              <Burst TYPE="STRING" VALUE=""/>
              </Limit>
            <MultiPort TYPE="LIST">
              <SourcePorts TYPE="STRING" VALUE=""/>
              <DestPorts TYPE="STRING" VALUE=""/>
              <Ports TYPE="STRING" VALUE=""/>
              </MultiPort>
            <MatchMark TYPE="STRING" VALUE=""/>
            <Owner TYPE="LIST">
              <Uid TYPE="INT" VALUE="0"/>
              <Gid TYPE="INT" VALUE="0"/>
              <Pid TYPE="INT" VALUE="0"/>
              <Sid TYPE="INT" VALUE="0"/>
              </Owner>
            <State TYPE="STRING" VALUE=""/>
            <Unclean TYPE="STRING" VALUE=""/>
            <MatchTos TYPE="STRING" VALUE=""/>
            <TTLMatch TYPE="INT" VALUE="0"/>
            </Match>
          </MatchList>
          <Target TYPE="LIST">
            <TargetName TYPE="STRING" VALUE=""/>
            <Log TYPE="LIST">
              <Level TYPE="STRING" VALUE=""/>
              <Prefix TYPE="STRING" VALUE=""/>
              <TcpSequence TYPE="BOOL" VALUE="FALSE"/>
              <TcpOptions TYPE="BOOL" VALUE="FALSE"/>
              <IpOptions TYPE="BOOL" VALUE="FALSE"/>
              </Log>
            <SetMark TYPE="STRING" VALUE=""/>
            <RejectType TYPE="STRING" VALUE=""/>
            <SetTos TYPE="STRING" VALUE=""/>
            <SNATtoSource TYPE="STRING" VALUE=""/>
            <DNATtoDest TYPE="STRING" VALUE=""/>
            <MASQtoPort TYPE="STRING" VALUE=""/>
            <REDIRtoPort TYPE="STRING" VALUE=""/>
            <TTL TYPE="LIST">
              <TTLSet TYPE="INT" VALUE="0"/>
              <TTLDec TYPE="INT" VALUE="0"/>
              <TTLInc TYPE="INT" VALUE="0"/>
              </TTL>
            <ULOG TYPE="LIST">
              <ULOGnlgroup TYPE="STRING" VALUE=""/>
              <ULOGprefix TYPE="STRING" VALUE=""/>
              <ULOGcprange TYPE="INT" VALUE="0"/>
              <ULOGqthreshold TYPE="INT" VALUE="0"/>
              </ULOG>
            </Target>
        </Rule>
      </RuleList>
    </Firewall>

    </datatree>
  </adm_context>
 
