<?xml version="1.0"?>
<adm_context VERSION="0">
  <id NAME="netconf" SERIAL="1">
    <null/>
    <null/>
    </id>
  <datatree>
  <HardwareList TYPE="LIST" ANONYMOUS="TRUE">
    <Hardware TYPE="LIST">
      <Name TYPE="STRING" VALUE=""/>
      <Description TYPE="STRING" VALUE=""/>
      <Type  TYPE="STRING" VALUE=""/>

      <Card TYPE="LIST">
        <ModuleName TYPE="STRING" VALUE=""/>
        <Type TYPE="STRING" VALUE=""/>
        <IoPort TYPE="STRING" VALUE=""/>
        <IoPort1 TYPE="STRING" VALUE=""/>
        <IoPort2 TYPE="STRING" VALUE=""/>
        <Mem TYPE="STRING" VALUE=""/>
        <IRQ TYPE="STRING" VALUE=""/>
        <DMA0 TYPE="INT" VALUE=""/>
        <DMA1 TYPE="INT" VALUE=""/>
        <ChannelProtocol TYPE="STRING" VALUE=""/>
        <Firmware TYPE="STRING" VALUE=""/>
        </Card>

      <Modem TYPE="LIST">
        <DeviceName TYPE="STRING" VALUE=""/>
        <BaudRate TYPE="INT" VALUE="0"/>
        <FlowControl TYPE="STRING" VALUE=""/>
        <ModemVolume TYPE="INT" VALUE="0"/>
        <DialCommand TYPE="STRING" VALUE=""/>
        <InitString TYPE="STRING" VALUE=""/>
        </Modem>

      </Hardware>
    </HardwareList>
    </datatree>
  </adm_context>
 
