<?xml version="1.0"?>
<adm_context VERSION="0">
  <id NAME="netconf" SERIAL="1">
    <null/>
    <null/>
    </id>
  <datatree>
<Netconf TYPE="LIST">

  <DeviceList TYPE="LIST" ANONYMOUS="TRUE">
    <Device TYPE="LIST">
      <DeviceId TYPE="STRING"/>

      <DeviceName TYPE="STRING"/>
      <OnBoot TYPE="BOOL"/>
      <AllowUser TYPE="BOOL"/>

      <AutoIp TYPE="STRING"/>

      <IP TYPE="STRING"/>
      <Netmask TYPE="STRING"/>
      <DefaultGW TYPE="STRING"/>

      <Hostname TYPE="STRING"/>
      <Domain TYPE="STRING"/>
      <AutoDNS TYPE="BOOL"/>
 
      <StaticRoutes TYPE="LIST" ANONYMOUS="TRUE">
        <Route TYPE="LIST">
          <Adress TYPE="STRING"/>
          <Netmask TYPE="STRING"/>
          </Route>
        </StaticRoutes>

      <Dialup  TYPE="LIST">
        <ProviderName TYPE="STRING"/>
        <MSN TYPE="INTEGER"/>
        <Login TYPE="STRING"/>
        <Password TYPE="STRING"/>
        <Authentication TYPE="STRING"/>

        <PPPOptions TYPE="LIST">
          <Option TYPE="STRING"/>
          </PPPOptions>

        <DialinServer TYPE="BOOL"/>
        <ChannelBundling TYPE="BOOL"/>
        <EncapMode TYPE="STRING"/>
        <HangupTimeout TYPE="INTEGER"/>
        <DialMode TYPE="STRING"/>

        <Callback TYPE="LIST">
          <Number TYPE="STRING"/>
          <Delay TYPE="INTEGER"/>
          <Restrict TYPE="BOOL"/>
          <CBCP TYPE="BOOL"/>
          </Callback>

        <Compression TYPE="LIST">
          <VJTcpIp TYPE="BOOL"/>
          <VJID TYPE="BOOL"/>
          <AdressControl TYPE="BOOL"/>
          <ProtoField TYPE="BOOL"/>
          <BSD TYPE="BOOL"/>
          <CCP TYPE="BOOL"/>
          </Compression>        
        </Dialup>

      </Device>
    </DeviceList>

  <ProfileList TYPE="LIST" ANONYMOUS="TRUE">
    <Profile TYPE="LIST">
      <ProfileName TYPE="STRING"/>
      <ActiveDevices TYPE="LIST" ANONYMOUS="TRUE">
        <DeviceId TYPE="STRING"/>
      </ActiveDevices>
      <DNS TYPE="LIST">
        <Domain TYPE="STRING"/>
        <ServerList TYPE="LIST" ANONYMOUS="TRUE">
          <IP TYPE="STRING">
          </ServerList>
        </DNS>
      </Profile>   
    </ProfileList>

  <HardwareList TYPE="LIST" ANONYMOUS="TRUE">
    <Card TYPE="LIST">
      <CardName TYPE="STRING"/>
      <DeviceName TYPE="STRING"/>
      <IoPort TYPE="INTEGER"/>
      <IoPort1 TYPE="INTEGER"/>
      <IoPort2 TYPE="INTEGER"/>
      <Mem TYPE="STRING"/>
      <IRQ TYPE="INTEGER"/>
      <DMA0 TYPE="INTEGER"/>
      <DMA1 TYPE="INTEGER"/>
      <ChannelProtocol TYPE="STRING"/>
      </Card>
    </HardwareList>

  <ProviderList TYPE="LIST" ANONYMOUS="TRUE">
    <Provider TYPE="LIST">
      <ProviderName TYPE="STRING"/>
        <Country TYPE="STRING"/>
        <Flag TYPE="STRING"/>
        <City TYPE="STRING"/>
        <Name TYPE="STRING"/>
        <Type TYPE="STRING"/>
        <User TYPE="STRING"/>
        <Pass TYPE="STRING"/>
        <Phone TYPE="STRING"/>
        <DNS TYPE="STRING"/>
        <Encaps TYPE="STRING"/>
        <Layer2 TYPE="STRING"/>
        <Auth TYPE="STRING"/>
        <AutoIp TYPE="STRING"/>     
      </Provider>
    </ProviderList>

  <Accounting>
    </Accounting>

  <Traffic>
    </Traffic>

  <NetworkList TYPE="LIST" ANONYMOUS="TRUE">
    <Network TYPE="LIST">
      <NetName TYPE="STRING"/>
      <NetMask TYPE="STRING"/>
      <NetBits TYPE="INTEGER"/>
      </Network>
    </NetworkList>

  <Firewall TYPE="LIST">

    <GUIMode TYPE="STRING/>

    <EasySetup TYPE="LIST">
      <Level TYPE="STRING"/>
      <ServiceList TYPE="LIST" ANONYMOUS="TRUE">
        <ServiceName TYPE="STRING"/>
        </ServiceList>
      <SecureDeviceList TYPE="LIST" ANONYMOUS="TRUE">
        <DeviceId TYPE="STRING">
        </SecureDeviceList>
      </EasySetup>

    <MediumSetup TYPE="LIST">
      <InDeviceList TYPE="LIST" ANONYMOUS="TRUE">
        <DeviceId TYPE="STRING">
        </InDeviceList>

      <OuterDeviceList TYPE="LIST" ANONYMOUS="TRUE">
        <DeviceId TYPE="STRING">
        </OuterDeviceList>

      <MasqList TYPE="LIST" ANONYMOUS="TRUE">
        <MasqEntry>
          <InDevice TYPE="STRING"/>
          <OutDevice TYPE="STRING"/>
          <Ports TYPE="STRING"/>
          </MasqEntry>
        </MasqList>
      </MediumSetup>

    <ChainList TYPE="LIST" ANONYMOUS="TRUE">
      <Chain TYPE="LIST">
        <Name TYPE="STRING"/>
        <Table TYPE="STRING"/>
        <Policy TYPE="STRING"/>
        </Chain>
      </ChainList>

    <RuleList TYPE="LIST" ANONYMOUS="TRUE">
      <Rule TYPE="LIST">
        <RuleName  TYPE="STRING"/>
        <RuleGroup  TYPE="STRING"/>
        <Protocol TYPE="STRING"/>
        <Source TYPE="STRING"/>
        <Destination TYPE="STRING"/>
        <Jump TYPE="STRING"/>
        <Chain TYPE="STRING"/>
        <InInterface TYPE="STRING"/>
        <OutInterface TYPE="STRING"/>
        <Fragment TYPE="STRING"/>
        <MatchList TYPE="LIST" ANONYMOUS="TRUE">
          <Match TYPE="LIST">
            <Tcp TYPE="LIST">
              <SourcePorts TYPE="STRING"/>
              <DestPorts TYPE="STRING"/>
              <TcpFlags TYPE="STRING"/>
              <Syn TYPE="STRING"/>
              <TcpOption TYPE="STRING"/>
              </Tcp>
            <Udp TYPE="LIST">
              <SourcePorts TYPE="STRING"/>
              <DestPorts TYPE="STRING"/>
              </Udp>
            <Icmp TYPE="LIST">
              <IcmpType TYPE="STRING"/>
              </Icmp>
            <Mac TYPE="LIST">
              <MacSource TYPE="STRING"/>
              </Mac>
            <Limit TYPE="LIST">
              <Rate TYPE="STRING"/>
              <Burst TYPE="STRING"/>
              </Limit>
            <MultiPort TYPE="LIST">
              <SourcePorts TYPE="STRING"/>
              <DestPorts TYPE="STRING"/>
              <Ports TYPE="STRING"/>
              </MultiPort>
            <MatchMark/>
            <Owner TYPE="LIST">
              <Uid TYPE="INTEGER"/>
              <Gid TYPE="INTEGER"/>
              <Pid TYPE="INTEGER"/>
              <Sid TYPE="INTEGER"/>
              </Owner>
            <State TYPE="STRING"/>
            <Unclean TYPE="STRING"/>
            <MatchTos TYPE="STRING"/>
            <TTLMatch TYPE="INTEGER"/>
            </Match>
          </MatchList>
          <Target TYPE="LIST">
            <TargetName TYPE="STRING"/>
            <Log TYPE="LIST">
              <Level TYPE="STRING"/>
              <Prefix TYPE="STRING"/>
              <TcpSequence TYPE="BOOL"/>
              <TcpOptions TYPE="BOOL"/>
              <IpOptions TYPE="BOOL"/>
              </Log>
            <SetMark TYPE="STRING"/>
            <RejectType TYPE="STRING"/>
            <SetTos TYPE="STRING"/>
            <SNATtoSource TYPE="STRING"/>
            <DNATtoDest TYPE="STRING"/>
            <MASQtoPort TYPE="STRING"/>
            <REDIRtoPort TYPE="STRING"/>
            <TTL TYPE="LIST">
              <TTLSet TYPE="INTEGER"/>
              <TTLDec TYPE="INTEGER"/>
              <TTLInc TYPE="INTEGER"/>
              </TTL>
            <ULOG>
              <ULOGnlgroup TYPE="STRING"/>
              <ULOGprefix TYPE="STRING"/>
              <ULOGcprange TYPE="INTEGER"/>
              <ULOGqthreshold TYPE="INTEGER"/>
              </ULOG>
            </Target>
        </Rule>
      </RuleList>
    </Firewall>

  </Netconf>
    </datatree>
  </adm_context>
 
