<?xml version="1.0"?>
<adm_context VERSION="0">
  <id NAME="netconf" SERIAL="1">
    <null/>
    <null/>
    </id>
  <datatree>
<Netconf>

  <DeviceList>
    <Device>
      <DeviceName TYPE="STRING"/>
      <Hostname TYPE="STRING"/>
      <IP TYPE="STRING"/>
      <Netmask TYPE="STRING"/>

      <StaticRoutes>
        <Route TYPE="STRING"/>
        </StaticRoutes>

      <Dialup>
        <ProviderName TYPE="STRING"/>
        <MSN TYPE="INTEGER"/>
        <Login TYPE="STRING"/>
        <Password TYPE="STRING"/>
        <Authentication TYPE="STRING"/>

        <PPPOptions TYPE="LIST">
          <Option TYPE="STRING"/>
          </PPPOptions>

        <DialinServer TYPE="BOOL"/>
        <ChannelBundling TYPE="BOOL"/>
        <EncapMode TYPE="STRING"/>
        <HangupTimeout TYPE="INTEGER"/>
        <DialMode TYPE="STRING"/>

        <Callback TYPE="LIST">
          <Number TYPE="STRING"/>
          <Delay TYPE="INTEGER"/>
          <Restrict TYPE="BOOL"/>
          <CBCP TYPE="BOOL"/>

        <Compression>
          <VJTcpIp TYPE="BOOL"/>
          <VJID TYPE="BOOL"/>
          <AdressControl TYPE="BOOL"/>
          <ProtoField TYPE="BOOL"/>
          <BSD TYPE="BOOL"/>
          <CCP TYPE="BOOL"/>
          </Compression>        
        </Dialup>

      </Device>
    </DeviceList>

  <ProfileList>
    <Profile>
      <ProfileName/>
      <ActiveDevices>
        <DeviceName/>
      </ActiveDevices>
      <DNS>
        <Domain/>
        <ServerList>
          <IP>
          </ServerList>
        </DNS>
      </Profile>   
    </ProfileList>

  <HardwareList>
    <Card>
      <CardName/>
      <DeviceName/>
      <IoPort/>
      <IoPort1/>
      <IoPort2/>
      <Mem/>
      <IRQ/>
      <DMA0/>
      <DMA1/>
      <Channel Protocol>
        <Euro ISDN/>
        <1TR6/>
      </Card>
    </HardwareList>

  <ProviderList>
    <Provider>
      <ProviderName/>
        <Country/>
        <Flag/>
        <City/>
        <Name/>
        <Type/>
        <User/>
        <Pass/>
        <Phone/>
        <DNS/>
        <Encaps/>
        <Layer2/>
        <Auth/>
        <Ipsetup/>     
      </Provider>
    </ProviderList>

  <Accounting>
    </Accounting>

  <Traffic>
    </Traffic>

  <Firewall>
    <FilterList>
      <Filter>
        <Protocol/>
        <Source/>
        <Destination/>
        <Jump/>
        <InInterface/>
        <OutInterface/>
        <Fragment/>
        <Match>
          <Tcp>
            <SourcePort/>
            <DestPort/>
            <TcpFlags/>
            <Syn/>
            <TcpOption/>
            </Tcp>
          <Udp>
            <SourcePort/>
            <DestPort/>
            </Udp>
          <Icmp>
            <IcmpType/>
            </Icmp>
          <Mac>
            <MacSource/>
            </Mac>
          <Limit>
            <Rate/>
            <Burst/>
            </Limit>
          
          </Match>
        </Filter>
      </FilterList>
    <NAT>
      </NAT>
    <Mangle>
      </Mangle>
    </Firewall>

  </Netconf>
    </datatree>
  </adm_context>
 
