<?xml version="1.0"?>
<adm_context VERSION="0">
  <id NAME="netconf" SERIAL="1">
    <null/>
    <null/>
    </id>
  <datatree>
  <ProfileList TYPE="LIST" ANONYMOUS="TRUE">
    <Profile TYPE="LIST">
      <ProfileName TYPE="STRING" VALUE=""/>

      <Active TYPE="BOOL" VALUE="FALSE"/>

      <ActiveDevices TYPE="LIST" ANONYMOUS="TRUE">
        <DeviceId TYPE="STRING" VALUE=""/>
      </ActiveDevices>

      <ActiveIPsecs TYPE="LIST" ANONYMOUS="TRUE">
        <IPsecId TYPE="STRING" VALUE=""/>
      </ActiveIPsecs>
   
      <DNS TYPE="LIST">
        <Hostname TYPE="STRING" VALUE=""/>
        <Domainname TYPE="STRING" VALUE=""/>
        <PrimaryDNS TYPE="STRING" VALUE=""/>
        <SecondaryDNS TYPE="STRING" VALUE=""/>
        <TertiaryDNS TYPE="STRING" VALUE=""/>
        <SearchList TYPE="LIST" ANONYMOUS="TRUE">
          <Domain TYPE="STRING" VALUE=""/>
          </SearchList>
        </DNS>

        
      <HostsList TYPE="LIST" ANONYMOUS="TRUE">
        <Host TYPE="LIST">
          <IP TYPE="STRING" VALUE=""/>
          <Hostname TYPE="STRING" VALUE=""/>
          <AliasList TYPE="LIST" ANONYMOUS="TRUE">
            <Alias TYPE="STRING" VALUE=""/>
            </AliasList>
            <Comment TYPE="STRING" VALUE=""/>
          </Host>
        </HostsList>

      </Profile>   
    </ProfileList>
    </datatree>
  </adm_context>
