<?xml version="1.0"?>
<adm_context VERSION="0">
  <id NAME="netconf" SERIAL="1">
    <null/>
    <null/>
    </id>
  <datatree>
  <ProviderList TYPE="LIST" ANONYMOUS="TRUE">
    <Provider TYPE="LIST">
      <ProviderName TYPE="STRING" VALUE=""/>
        <Country TYPE="STRING" VALUE=""/>
        <Flag TYPE="STRING" VALUE=""/>
        <City TYPE="STRING" VALUE=""/>
        <Name TYPE="STRING" VALUE=""/>
        <Type TYPE="STRING" VALUE=""/>
        <User TYPE="STRING" VALUE=""/>
        <Pass TYPE="STRING" VALUE=""/>
        <Phone TYPE="STRING" VALUE=""/>
        <DNS TYPE="STRING" VALUE=""/>
        <Encaps TYPE="STRING" VALUE=""/>
        <Layer2 TYPE="STRING" VALUE=""/>
        <Auth TYPE="STRING" VALUE=""/>
        <AutoIp TYPE="STRING" VALUE=""/>     
      </Provider>
    </ProviderList>
    </datatree>
  </adm_context>
 
