<?xml version="1.0"?>
<adm_context VERSION="0">
  <id NAME="netconf" SERIAL="1">
    <null/>
    <null/>
    </id>
  <datatree>
  <HardwareList TYPE="LIST" ANONYMOUS="TRUE">
    <Card TYPE="LIST">
      <CardName TYPE="STRING" VALUE=""/>
      <DeviceName TYPE="STRING" VALUE=""/>
      <IoPort TYPE="INT" VALUE="0"/>
      <IoPort1 TYPE="INT" VALUE="0"/>
      <IoPort2 TYPE="INT" VALUE="0"/>
      <Mem TYPE="STRING" VALUE=""/>
      <IRQ TYPE="INT" VALUE="0"/>
      <DMA0 TYPE="INT" VALUE="0"/>
      <DMA1 TYPE="INT" VALUE="0"/>
      <ChannelProtocol TYPE="STRING" VALUE=""/>
      </Card>
    <Modem TYPE="LIST">
      <ModemName TYPE="STRING"/>
      <DeviceName TYPE="STRING"/>
      <BaudRate TYPE="INTEGER"/>
      <FlowControl TYPE="STRING"/>
      <ModemVolume TYPE="INTEGER"/>
      <DialCommand TYPE="STRING"/>
      </Modem>
    </HardwareList>
    </datatree>
  </adm_context>
 
